services:
  aws-mock:
    image: motoserver/moto:latest
    ports:
      - "4566:4566"
    environment:
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_REGION: "us-east-1"
      MOTO_PORT: "4566"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4566 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "46379:6379"
    command: [ "redis-server" ]
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data: